# Generated by Django 5.2.3 on 2025-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moshina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Moshina',
                'ordering': ['-year'],
            },
        ),
    ]
