# Generated by Django 5.2.3 on 2025-06-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moshina',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
